- manifests/haproxy.yaml
- manifests/machineid.yaml
- manifests/metallb.yaml
- zarf.yaml
This replaces the problematic volume mount to generate a machine-id with a initcontainer daemonset to do the same without the janky docker mount issues. Also removed `onRemote` action that would break due to [this](https://github.com/defenseunicorns/zarf/issues/2130) Zarf issue.
> feat: use daemonset for machineid instead of docker mount

- .gitignore
- README.md
- zarf.yaml
add zarf var to provide additional k3d config arguments 
Fixes #
Relates to #
> fix: add zarf var for k3d_extra_args

- docs/MINIO.md
- values/minio-values.yaml
* Adds a default uds-loki user and corresponding bucket to support easier testing in CI/Dev for Loki, supporting ongoing work in https://github.com/defenseunicorns/uds-core/pull/156
* Removes test bucket
> feat: add loki user and bucket

- .gitignore
- README.md
- chart/templates/core-dns-custom.yaml
- docs/DNS.md
- zarf.yaml
Adds a coredns rewrite rule to point `*.uds.dev` to `host.k3d.internal` 
Fixes https://github.com/defenseunicorns/uds-k3d/issues/45
> feat: internal uds.dev resolution

- .github/workflows/build-test.yaml
- tasks.yaml
Removed redundant v in init tag in validate task.
Task was also trying to mv the zarf file to itself.
...
Fixes #
Relates to #
- [ x] Bug fix (non-breaking change which fixes an issue)
> fix: broken validate task

- .github/workflows/build-test.yaml
- .github/workflows/publish-image.yaml
- chart/templates/nginx.yaml
- docker/Dockerfile
- tasks.yaml
- zarf.yaml
Changes:
- Updated to latest patch releases for our custom k3s image (this should be short-lived since the zarf issue is resolved pending a release🤞)
- Adds `--no-progress` to tasks (uds/maru task output fix)
- Switches hostports for nginx 20443/20080 -> 443/80:
- This allows calls from the nodes destined for `uds.dev` addresses to resolve properly
- In particular this is beneficial for kube apiserver OIDC setup, when tying to keycloak in the cluster
- No adverse effects observed with this change (no extra privileges needed, all VS resolved as expected still)
- Also note that the "external" docker port binding hasn't changed, this was always 443/80
Fixes https://github.com/defenseunicorns/uds-k3d/issues/75
> chore: update to latest k3s patches, switch port mapping to standard ports

- README.md
Adds documentation for gracefully starting and stopping the K3d cluster to avoid `host.k3d.internal` resolution going stale upon Docker or Machine suspension, hibernation, shutdown, or restarts.
See the related issue below for more details. A recommended technical fix is provided within the issue, in case documentation is not sufficient enough for the end user.
Fixes #99
> chore(docs): graceful k3d shutdown and startup

- .github/workflows/build-test.yaml
- .github/workflows/publish-image.yaml
- docker/Dockerfile
- tasks.yaml
- zarf.yaml
Updates default k3s version to 1.30.4 (n-1 minor k8s version). Also updates testing matrix to 1.29, 1.30, 1.31 (latest patch versions).
Also removed/modified the placeholder versions in unused image build workflow/dockerfile.
> chore: update k3s test versions, default to 1.30.4

- chart/templates/localpath-rwx.yaml
Changes to support volume expansion to allow more things with uds-k3d, see upstream defaults: https://github.com/rancher/local-path-provisioner/blob/7a64e376245fcfd57d5d8a9ba6ab04f10f39f68e/deploy/chart/local-path-provisioner/templates/storageclass.yaml#L22
N/A
> chore: allow volumeexpansion in localpath storageclass

- README.md
- chart/Chart.yaml
- chart/templates/core-dns-custom.yaml
- chart/values.yaml
- docs/DNS.md
- docs/PORTS.md
- release-please-config.json
- tasks.yaml
- values/dev-stack-values.yaml
- zarf.yaml
Implements an alternative CoreDNS override that relies on UDS Core's base service mesh, Istio. Uses the admin and tenant ingress gateways as the rewrite targets to gracefully handle ungraceful Docker restarts/stops, where `host.k3d.internal` fails. Also handles the case of integrating and routing to potential/future alternative service meshes via CoreDNS (e.g., kong). Another added benefit is the end-user's ability to add further rewrites based on additional or alternative gateways, domains, subdomains, services and/or virtual services.
Fixes #99
> feat: implement graceful, modifiable UDS Core CoreDNS overrides

- chart/templates/nginx.yaml
- chart/values.yaml
- docs/DNS.md
Adds ability to override and add an additional gateway to the nginx config.
Relates to #98
> feat: add ability to support additional gateway/domain

- .github/workflows/build-test.yaml
- .github/workflows/publish-image.yaml
- .github/workflows/tag-and-release.yaml
- renovate.json
There's an issue in the Renovate dashboard with updating the `githubactions` dependency. For whatever reason, this sha listed doesn't match the version `v4.2.2`, so I'm updating that comment here to match other repos in a sort of blind attempt to fix the renovate issue(s).
Relates to #15
> chore: update sha/version reference for action/checkout

- .github/workflows/publish-image.yaml
- .github/workflows/tag-and-release.yaml
In order to perform the token exchange for the setup action the `id-token: write` permission needs to be added.
See https://github.com/defenseunicorns/uds-k3d/actions/runs/11746441220/job/32726338166
> fix: workflow permissions for cgr login

- chart/templates/nginx.yaml
- chart/values.yaml
- values/dev-stack-values.yaml
- zarf.yaml
Adds the ability to override the nginx domain.  This is helpful for scenarios in which you want to setup uds-k3d with a domain other than uds.dev.  It will be useful for setting up demo/dev environments that don't use uds.dev.  Useful for the runtime folks as they are doing [something nasty ](https://github.com/defenseunicorns/uds-runtime/blob/main/.github/test-infra/terraform/setup.sh#L11-L17)to get this working.
Fixes #
Relates to #
> feat: add ability to override nginx domain

- zarf.yaml
Adds a wait after k3d cluster deployment so that slow internet connections don't get errors.
...
Fixes #137
> fix: Add a wait after deploying the k3d cluster so that slow internet connections don't get errors

- .github/workflows/build-test.yaml
- README.md
- release-please-config.json
- zarf.yaml
BREAKING CHANGE: This package will now strictly enforce a k3d version of 5.7.1 or higher during deployment. While this will cause failures where it wouldn't have before, this aligns with the minimum known working k3d version that is compatible with this package.
This implements an action before deploy that uses standard linux/mac utilities to extract the k3d version and compare it to a minimum version (5.7.1). If the version is not at or above this version the deploy will fail with a message to the user to upgrade their version.
In addition this upgrades to the latest n-1 k3s image by default (`v1.31.4-k3s1`) and the latest patch versions of the latest 3 minors for CI.
Fixes https://github.com/defenseunicorns/uds-k3d/issues/139
> chore!: upgrade k3s version, add k3d version check

- .github/actions/debug-output/action.yaml
- .github/workflows/build-test.yaml
- zarf.yaml
Updates to latest 1.31.x by default and latest patch versions for CI testing.
N/A
> chore: update to k3s 1.31.6 by default

- chart/templates/localpath-rwx.yaml
Switches to the free latest cgr image for busybox to avoid dockerhub rate limiting.
N/A
> chore: switch to cgr busybox

- chart/templates/nginx.yaml
- values/minio-values.yaml
Updates to the latest minio image + adds renovate on the image tag.
Also switches to the quay unprivileged nginx image. This keeps us from any rate limiting issues, but also doesn't require us to mirror the image to GHCR. I also tested the chainguard nginx image, but that required running some additional `apk add` commands during startup (also requiring more privileges) so I pivoted to this simpler approach. This image should also be automatically renovated, or alternatively we can switch to one of the "less pinned" variants (`1.27-alpine` for example) to reduce the frequency of updates.
From uds-k3d repo:
```
uds run
```
From uds-core repo, deploy the base/SSO stack to validate the Istio gateways:
```
uds run -f tasks/create.yaml k3d-slim-dev-bundle
uds deploy …
```
> chore: update minio, switch to quay nginx

- .github/workflows/build-test.yaml
- tasks.yaml
- zarf.yaml
Updates to 1.32.4 by default and the surrounding minor versions for CI matrix.
N/A
> chore: update k3s to 1.32.4 by default

- .github/workflows/airgap-build-test.yaml
- .github/workflows/build-test.yaml
- .github/workflows/tag-and-release.yaml
- .gitignore
- README.md
- airgap/k3d/zarf.yaml
- airgap/uds-dev-stack/zarf.yaml
- chart/templates/localpath-rwx.yaml
- chart/templates/machineid.yaml
- chart/templates/nginx.yaml
- chart/values.yaml
- docs/AIRGAP.md
- tasks.yaml
- values/metallb-values.yaml
- values/minio-values.yaml
- zarf.yaml
Adds an airgap flavor for k3d.
New airgap flavor includes all of the `k3d` and `k3s` images to start the k3d cluster. These images are loaded using `docker load`. The `k3s` airgap images are mounted into the `k3d` cluster via a `docker volume` which is picked up by `k3s` when it starts in the container. This prevents the need for building a custom `k3s` image that includes those airgap images. Then all of the `uds-dev-stack` are loaded into the `k3d` cluster using `k3d image load`.
The restrictions on the `airgap` flavor is images are not swappable at deploy time so overwriting the `k3d` image is not possible. 
Fixes #173
> feat: `uds-k3d` airgap package flavor

- .github/workflows/airgap-build-test.yaml
- .github/workflows/build-test.yaml
Fixes an issue where renovate could not look up the action tag because it was missing a v.
Related to https://github.com/defenseunicorns/uds-k3d/issues/15
> fix: action tags in workflow comments

- .github/workflows/airgap-build-test.yaml
- .github/workflows/build-test.yaml
- .github/workflows/publish-image.yaml
- .github/workflows/tag-and-release.yaml
Adds MARU_AUTH before the setup task to ensure that remote task inclusion doesn't run the risk of getting rate limited.
Related to https://github.com/defenseunicorns/uds-common/pull/488
N/A
Validate that no 429s are seen in CI or locally.
> fix(ci): add maru auth for remote tasks

- airgap/uds-dev-stack/zarf.yaml
- renovate.json
- values/metallb-values.yaml
- zarf.yaml
Updates to latest metallb and fixes renovate grouping to group these PRs together in the future.
Fixes https://github.com/defenseunicorns/uds-k3d/pull/210
Fixes https://github.com/defenseunicorns/uds-k3d/pull/209
Fixes https://github.com/defenseunicorns/uds-k3d/pull/211
> chore: update metallb to 0.15.2, fix grouping in renovate

- .github/workflows/build-test.yaml
- tasks.yaml
- zarf.yaml
This reverts commit 10f53a2d92584015e3c68277408f7198f365bfe2.
We have been experiencing instability in uds-core CI, specifically around health probes. This allows us to consume other updates in uds-k3d while we dig into the issue further.
Example CI failures:
- https://github.com/defenseunicorns/uds-core/actions/runs/16527179194/job/46743496597?pr=1756
- https://github.com/defenseunicorns/uds-core/actions/runs/16527179134/job/46743403411?pr=1756
> chore: revert latest k3s patch versions

- airgap/k3d/zarf.yaml
Ran into an issue with docker not recognizing the format for the volume mount of ".:" and it wanted "$PWD:" instead. This fixes it so that it will properly set the volume mount reference to PWD instead of relative "."
> fix: docker volume reference pwd instead of .

- zarf.yaml
This PR adds an arg to set the ulimit for the number of files (nofile) along with a default value. This default value is what most systems will already be defaulting to and is safe.
The TLDR on why this is required is because the [upstream containerd systemd unit file](https://github.com/containerd/containerd/blob/main/containerd.service) [removed](https://github.com/containerd/containerd/commit/3ca39ef01608fdd44245c0173bf071682b3bfe3c) a config at some point and is depending on the default soft limit of 1024. This is failing with newer versions of uds-core (running guess now is because of the switch to ambient mode and more sockets being open). Other distributions actually kept this config in the unit file but mine (Arch btw) is using the one straight from upstream.
> feat: add default ulimit nofile for k3d

- .github/workflows/airgap-build-test.yaml
- .github/workflows/build-test.yaml
- .github/workflows/docs-shim.yaml
- .github/workflows/publish-image.yaml
- .github/workflows/tag-and-release.yaml
A few miscellaneous housekeeping things:
- adds milestone trigger to ensure we can run required CI on releases
- removes chainguard/registry1 logins (not actually used)
- adds docs-shim workflow so that required checks run on docs only PRs, plus updates paths
N/A
> chore: add milestone trigger, docs-shim
